<!DOCTYPE html>
<html lang="fr">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <title>MVC PHP Blog</title>

  <!-- CSS  -->
  <link href="public/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="public/css/index.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link rel="stylesheet" href="public/css/font-awesome-4.3.0/css/font-awesome.min.css"/>
  <link rel="shortcut icon" href="public/images/favicon (9).ico" type="image/x-icon">
  <link rel="icon" href="public/images/favicon (9).ico" type="image/x-icon">
</head>
<body>
<div id="navbar" class="navbar-fixed scrollspy">
  <nav class="grey darken-2">
    <div class="nav-wrapper container">
    	<div class="container"> <a href="index.html" class="brand-logo">Eniams Dev <3</a></div>

      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
      <ul class="right hide-on-med-and-down">

        <li><a href="index.html">Home</a></li>
         <li><a href="aboutUs.html">About Us</a></li>
         <li><a href="samplePost.html">Sample post</a></li>
        <li><a href="contactUs.html">Contact Us</a></li>


      </ul>
      <ul class="right side-nav" id="mobile-demo">
      	  <li><a href="index.html">Home</a></li>
         <li><a href="aboutUs.html">About Us</a></li>
         <li><a href="samplePost.html">Sample post</a></li>
        <li><a href="contactUs.html">Contact Us</a></li>

      </ul>
    </div>
  </nav>
  </div>

  <div id="index-banner" class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container valign">
        <br><br>
        <h1 class="header center grey-text text-darken-2">Casse les codes du code</h1>
        <div class="row center">
          <h5 class="header col s12 light grey-text text-darken-2">Have Fun...</h5>
        </div>
        <div class="row center">
          <a href="#startPosts" class="btn-floating btn-large waves-effect waves-light grey darken-2 head-link"><i class="fa fa-angle-double-down"></i></a>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><img src="App/public/images/main.jpg" alt="Unsplashed background img 2"></div>
  </div>