<?php
/**
 * Created by PhpStorm.
 * User: ismail
 * Date: 31/03/2017
 * Time: 08:24
 */
include ('header.phtml');
?>

    <div class="container">
    <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <h2>Dernier posts...</h2>
<?php foreach ($posts as $post): ?>

    <div class="post-preview">



        <a href="post.php?id=<?= $post->getId();?>">
            <h2 class="post-title">
                <?= $post->getTitre(); ?>
            </h2>
            <h3 class="post-subtitle">
                <?= $post->getExtrait(); ?>
            </h3>
        </a>
        <p class="post-meta">Ecrit par <strong><?= $post->getAuteur(); ?></strong></p>
    </div>
    <hr>




<?php endforeach;  ?>
    </div>
    </div>
    </div>
<div class="row">
    <div class="text-center">
        <ul class="pagination">
            <? for ($i =1; $i <= $totalPage; $i++)  :?>

            <li <?php if($i == $page): ?> class='active' <?php endif; ?>><a href="#"  > <?=$i;?> </a> </li>
<?php endfor;?>
        </ul>
    </div>

</div>
<?php include ('footer.phtml');