home:
    path: /blog
    controller: Home
    action: home
    view: home
showPost:
    path: /post
    controller: home
    action: showPost
    view: showPost
add:
    path: /add
    controller: Comment
    action: add
    view: addComment