home:
    path: /blog
    parameters: d*
    controller: Home
    action: home
    view: home
showPost:
    path: /post
    parameters: d*
    controller: Home
    action: showPost
    view: showPost
add:
    path: /add
    controller: Comment
    action: add
    view: addComment