home:
    path: /
    controller: Home
    action: home
    view: home
show:
    path: /show
    controller: Post
    action: show
    view: show
add:
    path: /add
    controller: Comment
    action: add
    view: addComment